# Generated by Django 5.1.15 on 2026-02-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'ticket_event',
                'indexes': [models.Index(fields=['city'], name='ticket_even_city_0ed586_idx'), models.Index(fields=['title'], name='ticket_even_title_d91ce6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('row', models.CharField(max_length=255)),
                ('seat', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_items', to='tickets.ticketevent')),
            ],
            options={
                'db_table': 'ticket_item',
                'indexes': [models.Index(fields=['price'], name='ticket_item_price_e5da1c_idx')],
            },
        ),
    ]
