# Generated by Django 5.1.15 on 2026-02-18 20:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketevent',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'city', config='italian'), name='event_search_gin'),
        ),
    ]
