# Generated by Django 5.1.15 on 2026-02-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketevent_event_search_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketevent',
            name='ticket_even_city_0ed586_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketevent',
            name='ticket_even_title_d91ce6_idx',
        ),
    ]
